name: Build (and, once secrets exist, push) Docker image

on:
  push:
    branches: [ Diego ]
  pull_request:
    branches: [ Diego ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Always build so CI proves the Dockerfile
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true           # loads into local daemon inside runner
          tags: tsm-mlops:test

      - name: Smoke-test CLI
        run: docker run --rm tsm-mlops:test python -m tsm_mlops.cli --help

      # These two steps only fire after secrets are added
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/Diego')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/Diego')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsm-mlops:${{ github.sha }}
