name: Build (and, once secrets exist, push) Docker image

on:
  push:
    branches: [Main]
  pull_request:
    branches: [Main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug step to check secrets
      - name: Check if secrets exist
        run: |
          if [ "${{ secrets.DOCKERHUB_USERNAME }}" != "" ]; then
            echo "DockerHub username is configured"
          else
            echo "DockerHub username is not configured"
          fi
          if [ "${{ secrets.DOCKERHUB_TOKEN }}" != "" ]; then
            echo "DockerHub token is configured"
          else
            echo "DockerHub token is not configured"
          fi

      # Always build so CI proves the Dockerfile
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true           # loads into local daemon inside runner
          tags: tsm-mlops:test

      - name: Smoke-test Docker image
        run: |
          # Override entrypoint to prevent automatic service startup
          docker run --rm --entrypoint python tsm-mlops:test --version

      # These two steps only fire after secrets are added
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/Diego')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/Diego')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsm-mlops:${{ github.sha }}
